const movies = [ 
{
  moviesName: "Interstellar",
  moviesUrl: `https://www.youtube.com/embed/2LqzF5WauAw?si=KU0hsYQzRyWbohAZ`,
  moviesPoster: "https://upload.wikimedia.org/wikipedia/fa/b/bc/Interstellar_film_poster.jpg",
  moviesInfo: "Interstellar is a 2014 epic science fiction film co-written, directed, and produced by Christopher Nolan. It stars Matthew McConaughey, Anne Hathaway, Jessica Chastain, Bill Irwin, Ellen Burstyn, Michael Caine, and Matt Damon. Set in a dystopian future where humanity is embroiled in a catastrophic blight and famine, the film follows a group of astronauts who travel through a wormhole near Saturn in search of a new home for humankind. Brothers Christopher and Jonathan Nolan wrote the screenplay, which had its origins in a script Jonathan developed in 2007 and was originally set to be directed by Steven Spielberg. Kip Thorne, a Caltech theoretical physicist and 2017 Nobel laureate in Physics,[4] was an executive producer, acted as a scientific consultant, and wrote a tie-in book, The Science of Interstellar. Cinematographer Hoyte van Hoytema shot it on 35 mm movie film in the Panavision anamorphic format and IMAX 70 mm. Principal photography began in late 2013 and took place in Alberta, Iceland, and Los Angeles. Interstellar uses extensive practical and miniature effects, and the company Double Negative created additional digital effects. Interstellar premiered in Los Angeles on October 26, 2014. In the United States, it was first released on film stock, expanding to venues using digital projectors. The film received positive reviews from critics and grossed over $681 million worldwide ($703 million after subsequent re-releases), making it the tenth-highest-grossing film of 2014. It has been praised by astronomers for its scientific accuracy and portrayal of theoretical astrophysics.[5][6][7] Interstellar was nominated for five awards at the 87th Academy Awards, winning Best Visual Effects, and received numerous other accolades.",
  moviesArtits: "Matthew McConaughey, Anne Hathaway, Jessica Chastain, Bill Irwin, Ellen Burstyn, Michael Caine",
  moviesCountry: "USA , UK",
  isSubtitled: "true",
  dateOfEcran: "26 October 2014",
  moviesLanguege:"English",
  moviesGenre: [`Fantasy`,`ScienceFiction`],
  imdb: `tt0816692`
},
{
  moviesName: "Mr. Nobody",
  moviesUrl: `https://www.youtube.com/embed/iJAP8q_iPOw?si=K4ogoNfLawfuVO-l`,
  moviesPoster: "https://upload.wikimedia.org/wikipedia/en/thumb/3/32/Mr._Nobody_%28film_poster%29.jpg/220px-Mr._Nobody_%28film_poster%29.jpg",
  moviesInfo: "Mr. Nobody is a 2009 science fiction drama film written and directed by Jaco Van Dormael and starring Jared Leto, Sarah Polley, Diane Kruger, Linh Dan Pham, Rhys Ifans, Natasha Little, Toby Regbo, and Juno Temple. It tells the life story of Nemo Nobody, a 118-year-old man who is the last mortal on Earth after the human race has achieved quasi-immortality. Nemo, memory fading, tells a doctor and journalist about his three main loves and his parents' divorce and the subsequent hardships he endured. The speculative narrative frequently changes course to investigate the alternate life paths that could have resulted from his making different decisions in his life, focusing on when he is nine, fifteen, and thirty-four. The film has a nonlinear narrative that incorporates the multiverse hypothesis.",
  moviesArtits: "Jared Leto, Sarah Polley, Diane Kruger, Linh Dan Pham, Rhys Ifans, Natasha Little, Toby Regbo, and Juno Temple",
  moviesCountry: "Belgium , Canada , France , Germany",
  isSubtitled: "false",
  dateOfEcran: "12 September 2009",
  moviesLanguege:"English",
  moviesGenre: [`Fantasy`,`Mystery`] ,
  imdb: `tt0485947`
},{
  moviesName: "Inception",
  moviesUrl: `https://www.youtube.com/embed/YoHD9XEInc0?si=rIXLKPMwEcHBMnQ7`,
  moviesPoster: "https://upload.wikimedia.org/wikipedia/en/2/2e/Inception_%282010%29_theatrical_poster.jpg",
  moviesInfo: "Inception is a 2010 science fiction action film written and directed by Christopher Nolan, who also produced the film with Emma Thomas, his wife. The film stars Leonardo DiCaprio as a professional thief who steals information by infiltrating the subconscious of his targets. He is offered a chance to have his criminal history erased, as payment for the implantation of another person's idea into a target's subconscious. The ensemble cast includes Ken Watanabe, Joseph Gordon-Levitt, Marion Cotillard, Elliot Page, Tom Hardy, Cillian Murphy, Tom Berenger, Dileep Rao and Michael Caine.",
  moviesArtits: "Leonardo DiCaprio, Ken Watanabe, Joseph Gordon-Levitt, Marion Cotillard, Elliot Page, Tom Hardy, Cillian Murphy, Tom Berenger, Michael Caine",
  moviesCountry: "USA , UK",
  isSubtitled: "true",
  dateOfEcran: "8 July 2010",
  moviesLanguege:"English",
  moviesGenre: [`ScienceFiction`,`Mystery`,`Fantasy`] ,
  imdb: `tt1375666`
},{
  moviesName: "The Prestige",
  moviesUrl: `https://www.youtube.com/embed/RLtaA9fFNXU?si=bNCxfwQoZN3lzpf9`,
  moviesPoster: "https://upload.wikimedia.org/wikipedia/en/thumb/d/d2/Prestige_poster.jpg/220px-Prestige_poster.jpg",
  moviesInfo: "The Prestige is a 2006 psychological thriller film directed by Christopher Nolan, written by Nolan and his brother Jonathan and based on the 1995 novel by Christopher Priest. It stars Hugh Jackman as Robert Angier and Christian Bale as Alfred Borden, rival stage magicians in Victorian London who feud over a perfect teleportation trick. The cast also features Michael Caine, Scarlett Johansson, Rebecca Hall, Andy Serkis, and David Bowie as Nikola Tesla. The film reunites Nolan with actors Bale and Caine from Batman Begins and returning cinematographer Wally Pfister, production designer Nathan Crowley, and editor Lee Smith. The Prestige was released on October 20, 2006, to positive reviews and grossed $109 million worldwide against a production budget of $40 million. It received Academy Award nominations for Best Art Direction and Best Cinematography.",
  moviesArtits: "Hugh Jackman , Christian Bale , Scarlett Johansson , Michael Caine , Rebecca Hall , Andy Serkis , David Bowie",
  moviesCountry: "USA , UK",
  isSubtitled: "true",
  dateOfEcran: "17 October 2006",
  moviesLanguege:"German",
  moviesGenre: [`Mystery`,`Fantasy`],
  imdb: `tt0482571`
},{
  moviesName: "The Lord of the Rings 1",
  moviesUrl: `https://www.youtube.com/embed/V75dMMIW2B4?si=V02UFEaST3mC1QJu`,
  moviesPoster: "https://upload.wikimedia.org/wikipedia/en/thumb/8/8a/The_Lord_of_the_Rings%2C_TFOTR_%282001%29.jpg/220px-The_Lord_of_the_Rings%2C_TFOTR_%282001%29.jpg",
  moviesInfo: "The Lord of the Rings: The Fellowship of the Ring is a 2001 epic fantasy adventure film directed by Peter Jackson from a screenplay by Fran Walsh, Philippa Boyens, and Jackson, based on 1954's The Fellowship of the Ring, the first volume of the novel The Lord of the Rings by J. R. R. Tolkien. The film is the first instalment in The Lord of the Rings trilogy. It features an ensemble cast including Elijah Wood, Ian McKellen, Liv Tyler, Viggo Mortensen, Sean Astin, Cate Blanchett, John Rhys-Davies, Billy Boyd, Dominic Monaghan, Orlando Bloom, Christopher Lee, Hugo Weaving, Sean Bean, Ian Holm, and Andy Serkis. Set in Middle-earth, the story tells of the Dark Lord Sauron, who seeks the One Ring, which contains part of his might, to return to power. The Ring has found its way to the young hobbit Frodo Baggins. The fate of Middle-earth hangs in the balance as Frodo and eight companions (who form the Fellowship of the Ring) begin their perilous journey to Mount Doom in the land of Mordor, the only place where the Ring can be destroyed. The Fellowship of the Ring was financed and distributed by American studio New Line Cinema, but filmed and edited entirely in Jackson's native New Zealand, concurrently with the other two parts of the trilogy.",
  moviesArtits: "Elijah Wood , Ian McKellen , Liv Tyler , Viggo Mortensen , Sean Astin , Cate Blanchett , John Rhys-Davies , Billy Boyd , Dominic Monaghan , Orlando Bloom , Christopher Lee , Hugo Weaving , Sean Bean , Ian Holm , Andy Serkis",
  moviesCountry: "USA , NEW Zealand",
  isSubtitled: "true",
  dateOfEcran: "10 December 2003",
  moviesLanguege:"English",
  moviesGenre: [`Historic`,`Fantasy`,`Action`] ,
  imdb: `tt0120737`
},{
  moviesName: "The Lord of the Rings 2",
  moviesUrl: `https://www.youtube.com/embed/LbfMDwc4azU?si=lzqyBru9t8IS98dW`,
  moviesPoster: "https://upload.wikimedia.org/wikipedia/en/thumb/f/fc/The_Lord_of_the_Rings%2C_T2T_%282002%29.jpg/220px-The_Lord_of_the_Rings%2C_T2T_%282002%29.jpg",
  moviesInfo: "The lord of the ring:The Two Towers : Awakening from a dream of Gandalf fighting the Balrog in Moria, Frodo Baggins finds himself, along with Samwise Gamgee, lost in the Emyn Muil near Mordor. They discover that they are being tracked by Gollum, a former bearer of the One Ring. Capturing Gollum, Frodo takes pity and allows him to guide them, reminding Sam that they will need Gollum's help to infiltrate Mordor Aragorn, Legolas, and Gimli pursue a band of Uruk-hai to save their companions Merry and Pippin, entering the kingdom of Rohan. The Uruk-hai are ambushed by a group of Rohirrim, allowing Merry and Pippin to escape into Fangorn Forest. Meeting Aragorn's group, the Rohirrim's leader Éomer explains that he and his men have been exiled by Rohan's king, Théoden, who is under the control of Saruman and his servant Gríma Wormtongue. Éomer believes Merry and Pippin were killed during the raid but leaves the group two horses. In Fangorn, Aragorn's group encounters Gandalf, who after his fight against the Balrog was resurrected as Gandalf the White to help save Middle-earth. Gandalf leads the trio to Rohan's capital, Edoras, where Gandalf frees Théoden from Saruman's control. Aragorn stops Théoden from executing Wormtongue, who flees. Learning of Saruman's plans to destroy Rohan with his Uruk-hai army, Théoden evacuates his citizens to the fortress of the Hornburg at Helm's Deep. Gandalf departs to find Éomer and his followers, hoping they will fight for their restored king. Aragorn befriends Théoden's niece, Éowyn, who becomes infatuated with him. When the refugees travelling to Helm's Deep are attacked by Saruman's Warg-riding Orcs, Aragorn falls from a cliff and is presumed dead. He is found by Théodred's horse Brego and rides to Helm's Deep, witnessing Saruman's army marching toward the fortress.",
  moviesArtits: "Elijah Wood , Ian McKellen , Liv Tyler , Viggo Mortensen , Sean Astin , Cate Blanchett , John Rhys-Davies , Bernard Hill , Christopher Lee , Billy Boyd , Dominic Monaghan , Orlando Bloom , Hugo Weaving , Miranda Otto , David Wenham , Brad Dourif , Karl Urban , Andy Serkis",
  moviesCountry: "USA , New Zealand",
  isSubtitled: "true",
  dateOfEcran: "5 December 2002",
  moviesLanguege:"English",
  moviesGenre: [`Historic`,`Fantasy`,`Action`] ,
  imdb: `tt0167261` 
},{
  moviesName: "The Lord of the rings 3",
  moviesUrl: `https://www.youtube.com/embed/y2rYRu8UW8M?si=YxrwpDMKEcrLLYW8`,
  moviesPoster: "https://upload.wikimedia.org/wikipedia/en/thumb/2/23/The_Lord_of_the_Rings%2C_TROTK_%282003%29.jpg/220px-The_Lord_of_the_Rings%2C_TROTK_%282003%29.jpg",
  moviesInfo: "The hobbit, Sméagol, is fishing with his cousin Déagol, who discovers the One Ring in the river. Sméagol's mind is ensnared by the Ring, and he kills his cousin for it. Increasingly corrupted physically and mentally, he retreats into the Misty Mountains and becomes known as Gollum. Centuries later, during the War of the Ring, Gandalf leads Aragorn, Legolas, Gimli, and King Théoden of Rohan to Isengard, where they reunite with Merry and Pippin. Gandalf retrieves Saruman's palantír, and the group returns to Edoras to celebrate their victory at Helm's Deep.[a] Pippin looks into the palantír, seeing Sauron and a burning tree. Gandalf deduces that the enemy plans to attack Gondor's capital Minas Tirith; he rides there to warn Gondor's corrupt steward Denethor. Pippin, who accompanies him, swears fealty to Denethor, whose now-dead heir Boromir had saved his life;[b] on Gandalf's instruction, Pippin triggers the lighting of the beacons, which call for help from Rohan.....",
  moviesArtits: "Elijah Wood , Ian McKellen , Liv Tyler , Viggo Mortensen , Sean Astin , Cate Blanchett , John Rhys-Davies , Bernard Hill , Billy Boyd , Dominic Monaghan , Orlando Bloom , Hugo Weaving , Miranda Otto , David Wenham , Karl Urban , John Noble , Andy Serkis , Ian Holm , Sean Bean",
  moviesCountry: "USA , NEW Zealand , Germany",
  isSubtitled: "true",
  dateOfEcran: "1 December 2003",
  moviesLanguege:"English",
  moviesGenre: [`Historic`,`Fantasy`,`Action`],
  imdb: `tt0167260`
},{
  moviesName: "Alien",
  moviesUrl: `https://www.youtube.com/embed/LjLamj-b0I8?si=TsoC3ivDiF6KSvhN`,
  moviesPoster: "https://upload.wikimedia.org/wikipedia/en/thumb/c/c3/Alien_movie_poster.jpg/220px-Alien_movie_poster.jpg",
  moviesInfo: "Alien is a 1979 science fiction horror film directed by Ridley Scott and written by Dan O'Bannon. Based on a story by O'Bannon and Ronald Shusett, it follows the crew of the commercial space tug Nostromo, who, after coming across a mysterious derelict spaceship on an uncharted planetoid, find themselves up against an aggressive and deadly extraterrestrial set loose on the Nostromo. The film stars Tom Skerritt, Sigourney Weaver, Veronica Cartwright, Harry Dean Stanton, John Hurt, Ian Holm, and Yaphet Kotto. It was produced by Gordon Carroll, David Giler, and Walter Hill through their company Brandywine Productions and was distributed by 20th Century-Fox. Giler and Hill revised and made additions to the script; Shusett was the executive producer. The Alien and its accompanying artifacts were designed by the Swiss artist H. R. Giger, while concept artists Ron Cobb and Chris Foss designed the more human settings",
  moviesArtits: "Tom Skerritt , Sigourney Weaver , Veronica Cartwright , Harry Dean Stanton , John Hurt , Ian Holm , Yaphet Kotto",
  moviesCountry: "USA , UK",
  isSubtitled: "true",
  dateOfEcran: "25 May 1979",
  moviesLanguege:"English",
  moviesGenre: [`ScienceFiction`,`Horror`] ,
  imdb: `tt0078748`
},{
  moviesName: "Alien 3",
  moviesUrl: `https://www.youtube.com/embed/KUTaNMJJBa8?si=fje3AatXAO8yKdF3`,
  moviesPoster: "https://upload.wikimedia.org/wikipedia/en/thumb/b/b9/Alien3_poster.jpg/220px-Alien3_poster.jpg",
  moviesInfo: "Following the events of Aliens, an egg hatches aboard the Colonial Marine spaceship Sulaco, releasing a facehugger. A fire starts and the ship's computer launches an escape pod containing Ellen Ripley, Newt, Hicks, and the damaged android Bishop; all four are in cryonic stasis. The pod crash-lands on Fiorina  161, a foundry and maximum-security correctional facility inhabited by male inmates with a genetic predisposition for antisocial behavior. The inmates recover the crashed pod and its passengers. The facehugger approaches inmate Thomas Murphy's dog, Spike.",
  moviesArtits: "Sigourney Weaver , Charles S. Dutton , Charles Dance , Lance Henriksen",
  moviesCountry: "USA",
  isSubtitled: "true",
  dateOfEcran: "22 May 1992",
  moviesLanguege:"English",
  moviesGenre: [`ScienceFiction`,`Horror`] ,
  imdb: `tt0103644`
},{
  moviesName: "Alien: Covenant",
  moviesUrl: ``,
  moviesPoster: "https://upload.wikimedia.org/wikipedia/en/3/33/Alien_Covenant_Teaser_Poster.jpg",
  moviesInfo: "In a prologue,[a] business magnate Peter Weyland speaks with his newly-activated android in a lakeside apartment. The android chooses the name  for himself after observing Michelangelo's statue. Weyland states that one day they will search for mankind's creator together. David comments on his unlimited lifespan as compared to Weyland's, which unsettles Weyland. In 2104 AD, 11 years after the Prometheus expedition, the colonization ship Covenant is seven years from reaching planet Origae-6 with 2,000 colonists in stasis and 1,140 human embryos in cold storage. The ship is monitored by Walter, an advanced android model that physically resembles David. When a neutrino burst damages the ship, Walter reanimates the human crewmates. The ship's captain, Jake Branson, is incinerated when his stasis pod malfunctions. While repairing the ship, the crew picks up a transmission of a human voice from a nearby planet which appears eminently more habitable than Origae-6. Despite the protests of Daniels, Branson's widow, that this new  planet is too good to be true, the new captain, Christopher Oram, decides they will investigate.",
  moviesArtits: "Michael Fassbender , Katherine Waterston , Billy Crudup , Danny McBride , Demián Bichir",
  moviesCountry: "USA , UK",
  isSubtitled: "true",
  dateOfEcran: "4 May 2017",
  moviesLanguege:"English",
  moviesGenre: [`ScienceFiction`,`Horror`] ,
  imdb: `tt2316204`
},{
  moviesName: "The Godfather",
  moviesUrl: ``,
  moviesPoster: "https://m.media-amazon.com/images/W/MEDIAX_792452-T2/images/I/71khjV-MoOS._AC_UF894,1000_QL80_.jpg",
  moviesInfo: "In 1945, the New York City Corleone family don, Vito Corleone, listens to requests during his daughter Connie's wedding to Carlo. Vito's youngest son Michael, a Marine who has thus far stayed out of the family business, introduces his girlfriend, Kay Adams, to his family at the reception. Johnny Fontane, a popular singer and Vito's godson, seeks Vito's help in securing a movie role. Vito sends his consigliere, Tom Hagen, to persuade studio president Jack Woltz to offer Johnny the part. Woltz refuses Hagen's request at first, but soon complies after finding the severed head of his prized stud horse in his bed....",
  moviesArtits: "Marlon Brando , Al Pacino , James Caan , Richard Castellano , Robert Duvall , Sterling Hayden , John Marley , Richard Conte , Diane Keaton",
  moviesCountry: "USA",
  isSubtitled: "true",
  dateOfEcran: "14 March 1972",
  moviesLanguege:"English",
  moviesGenre: [`Action`,`Gang`] ,
  imdb: `tt0068646`
},{
  moviesName: "The Godfather Part II",
  moviesUrl: `https://www.youtube.com/embed/9O1Iy9od7-A?si=afF50o5LfBeaUzqw`,
  moviesPoster: "https://m.media-amazon.com/images/M/MV5BMWMwMGQzZTItY2JlNC00OWZiLWIyMDctNDk2ZDQ2YjRjMWQ0XkEyXkFqcGdeQXVyNzkwMjQ5NzM@._V1_.jpg",
  moviesInfo: "In 1901, nine-year-old Vito Andolini flees his country after his whole family is killed in Corleone, Sicily when his father insults local Mafia chieftain Don Ciccio. Vito escapes to New York City and is registered on arrival as Vito Corleone. In 1917, Vito lives in New York with his wife, Carmela, and their infant son, Sonny. He loses his job due to the interference of Don Fanucci, a local Black Hand extortionist. His neighbor Peter Clemenza asks Vito to hide a bag of guns; as thanks, Clemenza enlists Vito's help in stealing a rug, which he gives to Carmela.",
  moviesArtits: "	Al Pacino , Robert Duvall , Diane Keaton , Robert De Niro , Talia Shire , Morgana King , John Cazale , Mariana Hill , Lee Strasberg",
  moviesCountry: "USA",
  isSubtitled: "true",
  dateOfEcran: "20 December 1974",
  moviesLanguege:"English",
  moviesGenre: [`Action`,`Gang`] ,
  imdb: `tt0071562`
},{
  moviesName: "The Godfather Part III",
  moviesUrl: `https://www.youtube.com/embed/UUkG37KSWf0?si=Y2QbbOiTp4LZ_rWu`,
  moviesPoster: "https://upload.wikimedia.org/wikipedia/en/5/55/GodfatherIII2.jpg",
  moviesInfo: "In 1979, Michael Corleone is approaching 60. Wracked with guilt over his ruthless rise to power, especially for having ordered his brother Fredo Corleone's murder, he donates millions to charitable causes. Michael and Kay are divorced; their children, Anthony and Mary, live with Kay. At a reception in Michael's honor at St. Patrick's Old Cathedral, which follows a papal order induction ceremony, Anthony tells his father that he is leaving law school to become an opera singer. Kay supports his decision; Michael wants Anthony to complete his law degree first but eventually agrees to let him go his own way. Kay reveals to Michael that she and Anthony know the truth about Fredo's death. Vincent Mancini, the out-of-wedlock son of Michael's long-dead brother Sonny, arrives at the reception. Michael's sister, Connie, arranges for Vincent to settle a dispute with his rival, Joey Zasa, but Zasa calls Vincent a bastard, and Vincent bites Zasa's ear. Michael, troubled by Vincent's temper yet impressed by his loyalty, agrees to include Vincent in the family business.",
  moviesArtits: "Al Pacino , Diane Keaton , Talia Shire , Andy García , Eli Wallach , Joe Mantegna , Bridget Fonda , George Hamilton , Sofia Coppola",
  moviesCountry: "USA",
  isSubtitled: "true",
  dateOfEcran: "20 December 1990",
  moviesLanguege:"English",
  moviesGenre:  [`Action`,`Gang`],
  imdb: `tt0099674`
},{
  moviesName: "The dark knight",
  moviesUrl: `https://www.youtube.com/embed/EXeTwQWrcwY?si=rtRVeFp0pyG6J1KS`,
  moviesPoster: "https://upload.wikimedia.org/wikipedia/en/1/1c/The_Dark_Knight_%282008_film%29.jpg",
  moviesInfo: "A gang of masked criminals robs a mafia-owned bank in Gotham City, betraying and killing each other until the sole survivor, the Joker, reveals himself as the mastermind and escapes with the money. The vigilante Batman, district attorney Harvey Dent, and police lieutenant Jim Gordon ally to eliminate Gotham's organized crime. Batman's true identity, the billionaire Bruce Wayne, publicly supports Dent as Gotham's legitimate protector, as Wayne believes Dent's success will allow Batman to retire, allowing him to romantically pursue his childhood friend Rachel Dawes, despite her relationship with Dent.",
  moviesArtits: "Christian Bale , Michael Caine , Heath Ledger , Gary Oldman , Aaron Eckhart , Maggie Gyllenhaal , Morgan Freeman",
  moviesCountry: "USA , UK",
  isSubtitled: "true",
  dateOfEcran: "14 July 2008",
  moviesLanguege:"English",
  moviesGenre: [`Action`,`Fantasy`,`Gang`],
  imdb: `tt0468569`
}
];

module.exports = movies